### PR TITLE
Add Qt5/Qt6 compatibility for IDA 9.2 support

### PR DESCRIPTION
**Pull request by mahmoudimus**
IDA 9.2 upgraded from Qt5 (PyQt5) to Qt6 (PySide6), breaking compatibility with the plugin. This commit adds version detection and compatibility layer to support both IDA 8.3-9.1 (Qt5) and IDA 9.2+ (Qt6).

Changes:
  - Add IDAVersionInfo class for kernel version detection
  - Conditionally import PySide6 for IDA >= 9.2, PyQt5 for older versions
  - Add compatibility constants for renamed Qt enums:
    * BackgroundColorRole (Qt5) -> BackgroundRole (Qt6)
    * QPalette.Background (Qt5) -> QPalette.Window (Qt6)

Fixes AttributeError: 'PySide6.QtCore.Qt' has no attribute 'BackgroundColorRole'

### CODE REVIEW

**Comment by hasherezade** [comment]
Hi @mahmoudimus !
Thank you for your contribution. 
What is exactly the version of IDA that you tested it with? I just tried with `Version 9.2.250908 Windows x64` but it still crashes (just like the version before the refactoring when applied with IDA 9.2). Did you also encounter this issue in any configuration?

**Comment by hasherezade** [comment]
I see it works well with IDA 9.2 for Linux, so I am merging it. Thank you!
But if you have encountered the same issues on Windows as what I observed (crashing) please let me know if you was able to resolve them.

**Comment by mahmoudimus** [comment]
Hi @hasherezade - let me see. I will make a different PR once I can replicate what you're running into. Thanks for the fast merge.

**Comment by mahmoudimus** [comment]
I can't replicate your crash. I think maybe you should re-install on windows?

image
